---
name: Repository

on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
  workflow_dispatch:  # Added manual trigger

permissions:
  issues: write

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync labels
        uses: micnncim/action-label-syncer@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
